language: node_js
node_js:
  - "10"

git:
  depth: false
  submodules: false

branches:
  only:
  - master

before_script:
  - npm install -g gulp-cli
  - git config --global user.name $GIT_NAME
  - git config --global user.email $GIT_EMAIL
  - git config --global push.default simple
  - git fetch origin --tags
  - ./.travis-deploy-clone.sh

script:
  - ./.travis-check.sh
  - gulp build

after_success:
  - ./.travis-deploy-push.sh
